#!/usr/bin/env zsh

set -e # exit if any step has a nonzero exit code
set -o pipefail # including in the middle of a pipe

local title="$1"
local len=40
title="${title[1,$len]}"
printf '%-*s' "$len" "$title"
printf '-'
